# Generated by Django 2.2.5 on 2020-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
