# Generated by Django 2.2.5 on 2020-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_auto_20200305_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(),
        ),
    ]
