# Generated by Django 2.2.5 on 2020-03-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_auto_20200305_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officer.Grade'),
        ),
    ]
