# Generated by Django 2.2.5 on 2020-03-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_auto_20200305_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGradeTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officer.Course')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='officer.Teacher')),
            ],
        ),
    ]
